version: '3.4'
services:
  lehrmittel_laravel:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../../
    container_name: lehrmittel_laravel
    volumes:
      - ../../src:/var/www/html
    ports:
      - 8090:80
      - 8091:443
